#!/bin/bash
#arrow-detect.sh

arrowup='\[A'
arrowdown='\[B'
arrowrt='\[C'
arrowleft='\[D'
insert='\[2'
delete='\[3'

SUCCESS=0
OTHER=65

echo -n "press a key"
read -n3 key
echo -n "$key"|grep "$arrowup"
if ["$?" -eq $SUCCESS ]
then 
  echo "Up-arrow key pressed."
	exit $SUCCESS
fi

echo -n "$key"|grep "$arrowdown"
if ["$?" -eq $SUCCESS ]
then
  echo "down-arrow key pressed."
        exit $SUCCESS
fi

echo -n "$key"|grep "$arrowrt"
if ["$?" -eq $SUCCESS ]
then
  echo "Right-arrow key pressed."
        exit $SUCCESS
fi

echo -n "$key"|grep "$arrowleft"
if ["$?" -eq $SUCCESS ]
then
  echo "left-arrow key pressed."
        exit $SUCCESS
fi

echo -n "$key"|grep "$insert"
if ["$?" -eq $SUCCESS ]
then
  echo "\"Insert\" key pressed."
        exit $SUCCESS
fi

echo -n "$key"|grep "$delete"
if ["$?" -eq $SUCCESS ]
then
  echo "\"Delet\" key pressed."
        exit $SUCCESS
fi

echo "some  other key pressed."

exit $OTHER


