#!/bin/bash
MAXCOUNT=10
count=1

echo
echo "$MAXCOUNT random numbers:"
echo "-----------------"
while ["$count"-le$MAXCOUNT ]
do
        number=$RANDOM
        echo $number
        let "count+=1"
done
echo "---"
echo
exit 0
